# Generated by Django 2.2.14 on 2021-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210524_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_email',
            field=models.CharField(blank=True, default='Some user email', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_letter',
            field=models.CharField(blank=True, default='Some user message', max_length=1000),
        ),
    ]
