# Generated by Django 2.2.14 on 2021-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210524_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prioritize',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
