# Generated by Django 2.2.14 on 2021-05-24 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_prioritize'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 24, 8, 16, 33, 247055, tzinfo=utc)),
        ),
    ]
