# Generated by Django 2.2.14 on 2021-05-26 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_data_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 26, 21, 9, 47, 687421, tzinfo=utc)),
        ),
    ]
