# Generated by Django 2.2.14 on 2021-05-26 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210527_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 26, 23, 10, 7, 64687, tzinfo=utc)),
        ),
    ]
