# Generated by Django 2.2.14 on 2022-04-30 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210527_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='destination_email',
            field=models.EmailField(default='maksim.dvornik.2017@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
